### ISSUE TITLE
parameters_bump_cor_nicas.yml for HAFS-MOM6

### ISSUE THREAD

**Issue by YongzuoLi-NOAA** [JCSDA/soca#1]
## Description
Application of parameters_bump_cor_nicas.yml [link to yml](https://github.com/JCSDA/soca/blob/develop/test/testinput/parameters_bump_cor_nicas.yml) for HAFS-MOM6 NHC domain: 1/12 degree, 2413X964X55. 480 Processors are used (Produced 480 bump files)

(1) horizontal length-scale: value: 250.0e3  
(2) vertical length-scale: value: 10
(3) Error message: !!! ABORT in geom_setup_universe on task #000052: universe is not larger than halo A

netcdf MOM.res {
dimensions:
        Layer = 55 ;
        Time = UNLIMITED ; // (1 currently)
        lath = 964 ;
        lonh = 2413 ;
        latq = 964 ;
        lonq = 2413 ;

## Solution
Need to  change default
horizontal length-scale: value: 6000.0e3
vertical length-scale: value: 100
for HAFS-MOM6 domain

**Comment by YongzuoLi-NOAA** [comment]
I have run soca_error_covariance_toolbox.x parameters_bump_cor_nicas.yml [link to yml](https://github.com/JCSDA/soca/blob/develop/test/testinput/parameters_bump_cor_nicas.yml) at HAFS-MOM6 NHC domain using 480 processors. But the default length scale 6000e+3 is too large for HAFS-MOM6 NHC domain described above. It seems length scale is related to MOM6 domain size and number of processors used, right ? Please provide any related suggestions.

**Comment by travissluka** [comment]
@YongzuoLi-NOAA the files used for the soca ctests are for software correctness checks only. They should NOT be used for anything involving real science. 6,000km is far too large of a correlation length to use anywhere in the ocean. You should use the same lengths you have been using (~1.0 x rossby_radius) for your other regional experiments
