### ISSUE TITLE
ctest of soca_var.x crashed using parameters_bump_cor_nicas_scales in testinput/3dvarbump.yml

### ISSUE THREAD

**Issue by YongzuoLi-NOAA** [JCSDA/soca#2]
## Description
(1) I manually repeated the ctest for 3dvarbump successfully.
cd /work2/noaa/da/yongzuo/testv0/test_workdir/3dvarbump
 "/apps/gcc-10.2.0/openmpi-4.0.4/openmpi-4.0.4/bin/mpiexec" "-n" "2" "/work2/noaa/marine/yli/JEDI/soca-20230731/soca_build/bin/soca_var.x" "testinput/3dvarbump.yml"

(2) I replaced parameters_bump_cor_nicas with parameters_bump_cor_nicas_scales  in  testinput/3dvarbump.yml
Ran soca_var.x again as (1) and got the error below (crashed much earlier than my HAFS-MOM6 case). I will wait for you to pass this ctest to make sure the software is correct, right ?

-------------------------------------------------------------
Info     : --- Read local NICAS parameters
Info     :        Read NICAS local data
Info     :           Read NICAS data of task      1 from task      1
Info     :              Block: socn
Info     :                 Component: 1
Info     :              Block: tocn
Info     :                 Component: 1
Info     :              Block: uocn
Info     :                 Component: 1
Info     :              Block: vocn
Info     :                 Component: 1
!!! ABORT in nicas_read_local on task #000002: wrong size for dimension nc0a
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 1.

**Comment by YongzuoLi-NOAA** [comment]
@travissluka @guillaumevernieres Did anyone use parameters_bump_cor_nicas_scales in testinput/3dvarbump.yml for soca_var.x successfully ? @ShastriPaturi

**Comment by travissluka** [comment]
Those tests are not designed to work together. Look at the geometry resolution in the yaml files and you'll see that the 3dvarbump test runs on a different lower resolution grid

**Comment by YongzuoLi-NOAA** [comment]
Hi Travis,

Thank you for your response.

Yongzuo
